### ISSUE TITLE
I don't see the tray app after installing it

### ISSUE THREAD

**Issue by doroved** [riipandi/tauri-tray-app#1]
<img width="1350" alt="image" src="https://github.com/riipandi/tauri-tray-app/assets/30116541/ce530b8d-33f7-4025-945e-eb766991c067">

**Comment by riipandi** [comment]
In the attached screenshot you are already seeing. You can make the main window in the tray position if you don't need a large main window. My scaffolding was kept to a minimum so that it could be modified more freely.

If you need something like in the screenshot, you can refer to this commit: [26f5cde](https://github.com/riipandi/tauri-tray-app/commit/26f5cde55b366eef3f950d23f6adc849f8a90f3f)
